import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { ClerkProvider, SignedOut, SignInButton } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/Sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} dynamic>
      <html lang="en">
        <body
          className={`${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
            <AppSidebar />
            <Providers>
              <SidebarTrigger />
              <SignedOut>
                <SignInButton>
                  Sign me in
                </SignInButton>
              </SignedOut>
              {children}
            </Providers>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
    
  );
}
